
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class EditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmployee
     */
    public EditEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_EDept = new javax.swing.JTextField();
        jTextField_EJob = new javax.swing.JTextField();
        jTextField_EAge = new javax.swing.JTextField();
        jTextField_EID = new javax.swing.JTextField();
        jButton_CLEAR = new javax.swing.JButton();
        jButton_db_basic = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_UPDATE = new javax.swing.JButton();
        jButton_BACK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_EName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_EMail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Employee Id");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 82, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Job");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jTextField_EDept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField_EDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 270, -1));

        jTextField_EJob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_EJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EJobActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_EJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 270, -1));

        jTextField_EAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField_EAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 270, -1));

        jTextField_EID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField_EID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, -1));

        jButton_CLEAR.setBackground(new java.awt.Color(44, 62, 80));
        jButton_CLEAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_CLEAR.setForeground(new java.awt.Color(255, 255, 255));
        jButton_CLEAR.setText("Clear");
        jButton_CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CLEARActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 80, 34));

        jButton_db_basic.setBackground(new java.awt.Color(44, 62, 80));
        jButton_db_basic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_db_basic.setForeground(new java.awt.Color(255, 255, 255));
        jButton_db_basic.setText("Search");
        jButton_db_basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_db_basicActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_db_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jButton_UPDATE.setBackground(new java.awt.Color(44, 62, 80));
        jButton_UPDATE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        jButton_UPDATE.setText("Update");
        jButton_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UPDATEActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 34));

        jButton_BACK.setBackground(new java.awt.Color(44, 62, 80));
        jButton_BACK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_BACK.setForeground(new java.awt.Color(255, 255, 255));
        jButton_BACK.setText("Back");
        jButton_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BACKActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 80, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 132, -1, 30));

        jTextField_EName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField_EName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 270, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, -1));

        jTextField_EMail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField_EMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 270, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("Search Employee ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 27, -1, -1));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 202, 24));
        jLabel7.setText("HUMAN RESOURCE MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel7)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_db_basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_db_basicActionPerformed
        if(jTextField_EID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Input Employee Id");
        }
        else{
            int EID = Integer.parseInt(jTextField_EID.getText());
            ResultSet rs=null;

            try {

                Statement s = DBconnect.getConnection().createStatement();
                rs= s.executeQuery("SELECT * FROM `emp` WHERE EmpID = '"+EID+"'");

                while(rs.next()){
                    String eName  = rs.getString("EmpName");
                    jTextField_EName.setText(eName);

                    int eAge  = rs.getInt("Age");
                    jTextField_EAge.setText(String.valueOf(eAge));
                    
                    String eEmail  = rs.getString("EmpMail");
                    jTextField_EMail.setText(eEmail);
                    
                    String eJob  = rs.getString("Job");
                    jTextField_EJob.setText(eJob);

                    String eDept  = rs.getString("Department");
                    jTextField_EDept.setText(eDept);
                }

            } catch (Exception e) {
                System.out.println("Exception = " + e.getMessage());

            }
        }
    }//GEN-LAST:event_jButton_db_basicActionPerformed

    private void jButton_CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CLEARActionPerformed
        jTextField_EID.setText("");
        jTextField_EName.setText("");
        jTextField_EAge.setText("");
        jTextField_EMail.setText("");
        jTextField_EJob.setText("");
        jTextField_EDept.setText("");
    }//GEN-LAST:event_jButton_CLEARActionPerformed

    private void jButton_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UPDATEActionPerformed
        int e_id = Integer.parseInt(jTextField_EID.getText());
        String e_job = jTextField_EJob.getText();
        String e_dept = jTextField_EDept.getText();

        try {
            System.out.println("theeksahna popa");
            
            Statement s = DBconnect.getConnection().createStatement();
            System.out.println("theeksahna popa");
            String updateQuery = "UPDATE emp SET Job=(+e_job+),Department=(+e_dept+) WHERE EmpID = +e_id+";
            s.executeUpdate(updateQuery);
            System.out.println("theeksahna popa");
            
            JOptionPane.showMessageDialog(rootPane, "Added success");

        } catch (Exception e) {
            System.out.println("Exception = " + e);

        }
    }//GEN-LAST:event_jButton_UPDATEActionPerformed

    private void jButton_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BACKActionPerformed
        Adminform goToAdminform=new Adminform();
        goToAdminform.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_BACKActionPerformed

    private void jTextField_EJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EJobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BACK;
    private javax.swing.JButton jButton_CLEAR;
    private javax.swing.JButton jButton_UPDATE;
    private javax.swing.JButton jButton_db_basic;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_EAge;
    private javax.swing.JTextField jTextField_EDept;
    private javax.swing.JTextField jTextField_EID;
    private javax.swing.JTextField jTextField_EJob;
    private javax.swing.JTextField jTextField_EMail;
    private javax.swing.JTextField jTextField_EName;
    // End of variables declaration//GEN-END:variables
}
